### ISSUE TITLE
Published version out of sync

### ISSUE THREAD

**Issue by jegtnes** [terminalpixel/docpad-plugin-browsersync#5]
Hey @terminalpixel,

Thanks for your work on this, BrowserSync is so much better than LiveReload and I'm delighted to have the option of using that instead. One thing I've noticed, though: You've recently bumped the version of BrowserSync up to 2.6, but it's not published to npm/DocPad, so by installing it, it's still using 1.x.

As I needed BrowserSync2 for this project I'm working on, I [forked this repo](https://github.com/jegtnes/docpad-plugin-browsersync2) to publish a version using 2.x, but I'd love for it not to exist and there being only one DocPad BrowserSync plugin. Is there any way you could update the dependency version number of BrowserSync to be something that'll catch the entire BrowserSync 2 release, e.g. `^2.9.3` and publish that using `cake publish`? It'd be greatly appreciated!

Cheers,
Alex

**Comment by grantcodes** [comment]
Thanks!

I've updated the npm package to the latest version now.

**Comment by jegtnes** [comment]
Great, thank you very much for doing that :)
